# This file is used to configure
# the application properties for the development environment.
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-calm-bonus-a1laa4ro.ap-southeast-1.aws.neon.tech/cosmetic_web?sslmode=require
    username: cosmetic_web_owner
    password: xRwJd5LerY9F
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8080'